language: python

python:
    - "3.6"

before_install:
  - "pip install -U pip"
  - "python setup.py install"

install: pip3 install -r requirements.txt

script: python3 algorithms/init_aco_grad.py -f data/DATASET.csv
