language: python

python:
    - "3.6"

before_install:
  - "pip3 install cython"
  - "python setup.py install"

install: pip3 install -r requirements.txt

script: python3 src/init_acograd.py -f data/DATASET.csv
