language: python

python:
    - "3.8"

before_install:
  - "python setup.py install"

install: pip3 install -r requirements.txt

script: python3 src/algorithms/aco/init_acograd.py -f data/DATASET.csv
